### ISSUE TITLE
 When will the new version of zkcluster be released? 

### ISSUE THREAD

**Issue by jr981008** [vert-x3/vertx-zookeeper#104]
I am concerned that the cursorframework uses version 4.2. This library has conflicts in the project. The new version of zkcluster will solve this problem.

**Comment by vietj** [comment]
in which project are there conflicts with ?

**Comment by jr981008** [comment]
thanks your reply
in my own project, must use curatorframework 4.x, but the latest release vertx-zookeepr uses 2.x, there is an irreconcilable error, is it feasible to try to solve this problem with cumulative classloader? For example, like spring bootloader , because of security restrictions, I cannot use osgi

**Comment by jr981008** [comment]
i solve it use custome classloader.
