### ISSUE TITLE
vertx-zookeeper 4.0.0Beta/CR is not released

### ISSUE THREAD

**Issue by blindpirate** [vert-x3/vertx-zookeeper#107]
![image](https://user-images.githubusercontent.com/12689835/100425365-075d1580-30ca-11eb-85a1-3e5758d124f4.png)

Is this intentional?

**Comment by vietj** [comment]
it has not been yet released because it is not finished.

@stream-iori what is the status ?

**Comment by blindpirate** [comment]
@vietj I DMed @stream-iori , he said everything has been done for 4.0.0 and `master` is releaseable.

@tsegismont Can we release a `4.0.0` RC ?

**Comment by vietj** [comment]
@blindpirate I missed that, I think first we should add continuous integration for this then

**Comment by vietj** [comment]
I created a PR with the GitHub action CI : https://github.com/vert-x3/vertx-zookeeper/pull/108

**Comment by vietj** [comment]
there is currently one failure in the tests

https://github.com/vert-x3/vertx-zookeeper/runs/1466777157?check_suite_focus=true

does it ring a bell to anyone @stream-iori @tsegismont ?

any other can chime in and help :-)

**Comment by blindpirate** [comment]
@vietj I fixed that issue by https://github.com/vert-x3/vertx-zookeeper/pull/109

However, there seems still an issue in `ZKClusteredHATest.after()`, which is quite flaky on my local computer. Maybe we can merge #108 first to help catch all future failures?

**Comment by tsegismont** [comment]
@vietj the failing test is the test I added recently related to clustered consumer unregistration.

It seems #109 would fix it indeed (thanks @blindpirate )
