### ISSUE TITLE
Update the 4.0 deprecation and breaking changes wiki page

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-zookeeper#110]
https://github.com/vert-x3/wiki/wiki/4.0.0-Deprecations-and-breaking-changes

There are sections for the other cluster managers already.

**Comment by tsegismont** [comment]
@stream-iori can you please take care of this?

We'd like to release 4.0 next week. So if you can't do it by then, please come back to us. Thank you

**Comment by dtwitty** [comment]
Any update on this? Is there anything one should know when migrating a ZK-backed cluster from 3 to 4?
