### ISSUE TITLE
Ability to configure the retry policy

### ISSUE THREAD

**Issue by vmorsiani** [vert-x3/vertx-zookeeper#144]
#### Read me

Read this first before creating an issue:

- do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.
- you shall create a feature request only when it is general purpose enough.
- make sure that the feature is not already

#### Describe the feature

Right now the RetryPolicy is hardcoded (ExponentialBackoffRetryPolicy) and the only way to override this is buy providing directly a CuratorFramework instance when creating a ZookeeperClusterManager.

It is a bit overkill to do so when someone simply want to change the retry policy (for something like retry forever for retry elapsed or retry forever for example).

It would be nice to be able to provide the policy to be used in the json configuration.

#### Use cases

- allow the user to configure the retry policy without having to create a full CuratorFramework instance

#### Contribution

https://github.com/vert-x3/vertx-zookeeper/pull/143

**Comment by tsegismont** [comment]
Closed by #147 147
