### ISSUE TITLE
If I block the registration information for 'localOnly,' will there be any side effects?Or is it a bug?

### ISSUE THREAD

**Issue by goonover** [vert-x3/vertx-zookeeper#148]
### Questions

In the code, io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager#addRegistration.The method just call 'subsMapHelper.put(address, registrationInfo, promise);'.
As a result, there will be many nodes like '__vertx.net.fb433846-5f7f-4888-b8fd-4ef6a05825dc' in path '/io.vertx/__vertx.subs'.These ids should be generated by io.vertx.core.net.impl.NetSocketImpl#writeHandlerID.And when I debug, I found these registration is localOnly, why these registration info write to zookeeper

### Version

4.0.4

**Comment by goonover** [comment]
Will there be any side effects I modify the addRegistration to
 **
    @Override
    public void addRegistration(String address, RegistrationInfo registrationInfo, Promise<Void> promise) {
        if (registrationInfo.localOnly()) {
            return;
        }
        subsMapHelper.put(address, registrationInfo, promise);
    }
**

**Comment by tsegismont** [comment]
@goonover can you update to 4.4? `writeHandlerIDs` are disabled by default in this version (see https://github.com/eclipse-vertx/vert.x/issues/4625)

**Comment by goonover** [comment]
Yes, this problem can be sloved by updating version to 4.4.4

**Comment by tsegismont** [comment]
Thanks for letting us know!
