### ISSUE TITLE
Round robin with EventBus

### ISSUE THREAD

**Issue by teivah** [vert-x3/vertx-zookeeper#17]
Hello,

Thanks for this implementation, this is really useful.

I just wanted to raise the fact that the round robin publication from the EventBus does not seem to be managed. Indeed, the ZKAsyncMultiMap.get() method create a new ChoosableSet each time. It means the ChoosableSet.choose() method returns always the same element.

It might be great to implement a round-robin strategy (by caching the ChoosableSet for instance to make sure a new instance is not created each time?).

Thanks

**Comment by stream1984** [comment]
Looks like #10 
I will do my best to make vertx-zookeeper work fine before vert.x 3.3.0 release

**Comment by teivah** [comment]
Oh sorry you're right, this is the same issue.
Thanks for the support.

**Comment by teivah** [comment]
Duplicate of #10
