### ISSUE TITLE
EVENTBUS_PATH

### ISSUE THREAD

**Issue by xingxuan** [vert-x3/vertx-zookeeper#18]
Hello,
   the SUBS_MAP_NAME of the ClusteredEventBus on version 3.2.0 is "__vertx.subs", so  the param EVENTBUS_PATH of the ZKMap values should be  "/" + ZK_PATH_ASYNC_MULTI_MAP + "/__vertx.subs/"

**Comment by stream1984** [comment]
This issue has been fix in down stream, i will update upstream before vertx 3.3.0 release.
