### ISSUE TITLE
How to Config many zk address?

### ISSUE THREAD

**Issue by FattigerTao** [vert-x3/vertx-zookeeper#40]
If I have 3 zk virtual machine and how to config zk address? example 192.168.1.1 192.168.1.2 192.168.1.3

**Comment by stream1984** [comment]
There is zookeeper.json in your vert.x project, you can add zookeeper hosts in this config file.
[example](https://github.com/vert-x3/vertx-zookeeper/blob/master/src/test/resources/zookeeper.json)

**Comment by dinstone** [comment]
example:
{
  "zookeeperHosts":"192.168.1.1:2181, 192.168.1.2:2181, 192.168.1.3:2181",
  "sessionTimeout":5000,
  "connectTimeout":3000,
  "rootPath":"io.vertx",
  "retry": {
    "initialSleepTime":100,
    "intervalTimes":10000,
    "maxTimes":5
  }
}

**Comment by FattigerTao** [comment]
thanks all.

**Comment by takeseem** [comment]
@FattigerTao please close this issuse
