### ISSUE TITLE
HA is not working with ZooKeeper

### ISSUE THREAD

**Issue by jaceksokol** [vert-x3/vertx-zookeeper#55]
It looks like `clusterMap` in `HAManager` is not correctly populated with deployed HA verticles, thus when a nodes with a verticle deploy to be HA the verticle is not restored on any other node.

**Comment by stream1984** [comment]
That would be nice if you can provide some reproduce or some step to make it again in my local.

**Comment by SgrAlpha** [comment]
Same issue here, I've created a repo to reproduce it, https://github.com/SgrAlpha/vertx-zookeeper-failure, it's a very simple one, let me know if I didn't do it in the right way, thx.

**Comment by stream1984** [comment]
I would spend some time to look into it after my holiday

**Comment by rshensy** [comment]
Any update about this ticket? I am waiting for a deployment using ZooKeeper.

**Comment by vietj** [comment]
@stream1984 can you have a look please ?

**Comment by vietj** [comment]
@tsegismont can you investigate eventually ?

**Comment by romalev** [comment]
Just off top of my head - ZKSyncMap creates only ephemeral entries (ZKSyncMap holds HA information about vertices) which means its entries get deleted upon node's disconnect. 

`//sync map's node mode should be EPHEMERAL, as lifecycle of this path as long as verticle's.
  curator.create().creatingParentsIfNeeded().withMode(CreateMode.EPHEMERAL).forPath(keyPath, valueBytes);`

Now imagine we have two nodes [A,B] (each has one verticle deployed with ha enabled) within our cluster. Now suppose node A fails, ZK instance detects that and automatically remove corresponding entry within **syncMap** Then HAManager takes places (node B executes nodeLeft() on its nodeListener) and it tries to look up an entry that has been already deleted. 

`private synchronized void nodeLeft(String leftNodeID) {
    addHaInfoIfLost();

    checkQuorum();
    if (attainedQuorum) {
      checkSubs(leftNodeID);

      // Check for failover
      String sclusterInfo = clusterMap.get(leftNodeID);
      ... // rest of the code
}`

This can be potential cause for HA not working properly within ZK cluster manager.

**Comment by stream1984** [comment]
emm.
I would fix this in this week, i found that is about syncMap.

**Comment by stream1984** [comment]
Sorry for so long to fix this bug.
The change is a little, i have merge it to master, you can get diff from [here]
(https://github.com/vert-x3/vertx-zookeeper/commit/0b1762d92425e965c8962ab9c931478fc5efe256)

**Comment by romalev** [comment]
@stream1984 - thanks!

**Comment by romalev** [comment]
@stream1984 - there's one thing that bothers me in your fix so please correct if I am wrong. In production we always tend to have nodes running which means: 

`if (clusterNodes.getCurrentData().size() == 0) {
      getSyncMap("__vertx.haInfo").clear();
}`

this can get very rarely executed (say if once per year) so ZK instance can potentially bump into out-of-memory, can't it ? Since now HA-info entries are not ephemeral anymore. What do you think about all of this ? Thanks in advance.
