### ISSUE TITLE
JavaThread "Curator-PathChildrenCache-5719" daemon [_thread_blocked,

### ISSUE THREAD

**Issue by felix-laofan** [vert-x3/vertx-zookeeper#86]
[hs_err_pid35537.log](https://github.com/vert-x3/vertx-zookeeper/files/3341886/hs_err_pid35537.log)
use one day on line ,JVM error.   crazy!!!!!!!

**Comment by stream1984** [comment]
Hi
thread blocked is consequence but not cause.
please check the cause of OOM by jstack or JVM head dump.
