### ISSUE TITLE
Problem when subscribing to event bus destination that contians // in it.

### ISSUE THREAD

**Issue by NavidMitchell** [vert-x3/vertx-zookeeper#88]
I am trying to create an event bus subscription with a destination 
"srv://com.xx.xxx.gateway.services.IDataService" 

Which fails with the following error 
`java.lang.IllegalArgumentException: Invalid path string "/asyncMultiMap/__vertx.subs/srv://com.xx.xxx.gateway.services.IDataService/15692f3d-d659-4aae-90bf-084c0581ccac:172.31.99.215:61904" caused by empty node name specified @33`

This looks like this is caused because the key is automatically used as part of the znode path.

ZKMap.java line 61
`
 String keyPath(K k) {
    return mapPath + "/" + k.toString();
  }

 String valuePath(K k, Object v) {
    return keyPath(k) + "/" + v.toString();
  }
`

**Comment by stream1984** [comment]
Hi
I prefer compose `srv://` in code instead of save it into zk path.

**Comment by NavidMitchell** [comment]
Ok, thank you for your fast response.
