### ISSUE TITLE
Support Zookeeper 3.5.x 

### ISSUE THREAD

**Issue by jonheg** [vert-x3/vertx-zookeeper#89]
### Version

Which version(s) did you encounter this bug ?

All versions.

### Context

Vertx Zookeeper Clustermanager should support 3.5.x of Zookeeper Ensemble. 
Curator 4.0 is supporting both 3.4.x and 3.5.x : https://curator.apache.org/zk-compatibility.html

**Comment by stream-iori** [comment]
Hi

I am thinking upgrade to 3.5.x of ZK with Vert.x 4

**Comment by stream-iori** [comment]
see [#90]
