### ISSUE TITLE
removeIfPresent incorrectly implemented

### ISSUE THREAD

**Issue by doctorpangloss** [vert-x3/vertx-zookeeper#99]
### Version

`vertx-zookeeper:3.9.1`

### Context

https://github.com/vert-x3/vertx-zookeeper/blob/fdd14dcc2855091df15fbb11bc265fbd425fd71d/src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMap.java#L142

Observe `value` is sometimes `null`. `Should be Objects.equals`.

### Do you have a reproducer?

Simply call `removeIfPresent` on a key that doesn't exist.

**Comment by tsegismont** [comment]
Fixed in d87aec2
